# Generated by Django 5.2.4 on 2025-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friend_type', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField()),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('query_type', models.CharField(choices=[('hotels', 'Hotels'), ('restaurants', 'Restaurants'), ('attractions', 'Tourist Attractions'), ('flights', 'Flights'), ('general', 'General Search')], max_length=50)),
                ('results', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
