# Generated by Django 5.2.4 on 2025-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('available', 'Available'),
                    ('sold', 'Sold'),
                    ('reserved', 'Reserved'),
                    ('inactive', 'Inactive'),
                ],
                default='available'
            ),
        ),
    ]
